server:
  port: 8089
spring:
  mvc:
    cors:
      # 配置跨域请求所允许的来源，可以设置为 * 表示允许所有来源
      allowed-origins: "*"
      # 配置跨域请求所允许使用的 HTTP 方法
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      # 配置跨域请求所允许携带的请求头，可以设置为 * 表示允许所有请求头
      allowed-headers: "*"
  application:
    name: garbageSorting
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/garbage_sorting?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 123456


mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

garbageSorting:
  path: D:\img\

logging:
  level:
    springfox: error

